{% set name = "eerepr" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eerepr-{{ version }}.tar.gz
  sha256: 920cccbe498b2880f42ed39a2db8945f705b1497523c48b8d392c5380d511926

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
    - setuptools-scm
  run:
    - python >=3.7
    - earthengine-api

test:
  imports:
    - eerepr

about:
  home: https://github.com/aazuspan/eerepr
  summary: Code Editor-style reprs for Earth Engine data in a Jupyter notebook.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aazuspan
