{% set name = "eerepr" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/eerepr-{{ version }}.tar.gz
  sha256: a3c6f4d94ee19374aea2ff7ae9f2471f06649be5e18f9cb1cced8a00c2c20857

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - earthengine-api

test:
  requires:
    - python {{ python_min }}
  imports:
    - eerepr

about:
  home: https://github.com/aazuspan/eerepr
  summary: Code Editor-style reprs for Earth Engine data in a Jupyter notebook.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aazuspan
