{% set name = "eerepr" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/eerepr-{{ version }}.tar.gz
  sha256: 6b686643e3050cbc1892e0063dc6e238402397685123e09768be16e1f1fb7a94

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - earthengine-api

test:
  requires:
    - python {{ python_min }}
  imports:
    - eerepr

about:
  home: https://github.com/aazuspan/eerepr
  summary: Code Editor-style reprs for Earth Engine data in a Jupyter notebook.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aazuspan
