{% set name = "eerepr" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/eerepr-{{ version }}.tar.gz
  sha256: c25956d5c732c3bf6aeded21d26ae913c53628e46433553fe0d9ce46091ca940

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - earthengine-api

test:
  requires:
    - python {{ python_min }}
  imports:
    - eerepr

about:
  home: https://github.com/aazuspan/eerepr
  summary: Code Editor-style reprs for Earth Engine data in a Jupyter notebook.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aazuspan
